### ISSUE TITLE
KeyError when extracting spells0.unity3d

### ISSUE THREAD

**Issue by boingy** [HearthSim/UnityPack#10]
For example if I try to run bin/unityextract with spells0.unity3d:

```pytb
Traceback (most recent call last):
  File "unityextract", line 146, in <module>
    main()
  File "unityextract", line 143, in main
    exit(app.run())
  File "unityextract", line 56, in run
    self.handle_asset(asset)
  File "unityextract", line 82, in handle_asset
    if obj.type not in self.handle_formats:
  File "<snip>/unitypack/object.py", line 35, in type
    typename = self.asset.tree.type_trees[-150].type
KeyError: -150
```

**Comment by robert-nix** [comment]
Probably not the right fix, but my hack for it 

```diff
diff --git a/unitypack/object.py b/unitypack/object.py
index edef4c8..8c7db82 100644
--- a/unitypack/object.py
+++ b/unitypack/object.py
@@ -32,7 +32,7 @@ class ObjectInfo:
                                except NotImplementedError:
                                        typename = script.type.type[5:-1]  # Capture type name in PPtr<...>
                        else:
-                               typename = self.asset.tree.type_trees[-150].type
+                               typename = self.asset.tree.type_trees[self.type_id].type
                        self.asset.typenames[self.type_id] = typename
                return self.asset.typenames[self.type_id]

```

**Comment by jleclanche** [comment]
I think this is fixed, I haven't had issues extracting that file.

**Comment by jleclanche** [comment]
@Mischanix How is this not the right fix?
