### ISSUE TITLE
Object has no attribute 'read_uint'

### ISSUE THREAD

**Issue by ghost** [HearthSim/UnityPack#18]
Hi! 👋 

I've just installed UnityPack and when trying to run `unityextract` I get the following error message:

```
# micpringle at homer.local in ~/Desktop [12:00:51]
→ unityextract resources.assets
Traceback (most recent call last):
  File "/usr/local/bin/unityextract", line 4, in <module>
    __import__('pkg_resources').run_script('unitypack==0.6.1', 'unityextract')
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/site-packages/unitypack-0.6.1-py3.5.egg/EGG-INFO/scripts/unityextract", line 146, in <module>
    main()
  File "/usr/local/lib/python3.5/site-packages/unitypack-0.6.1-py3.5.egg/EGG-INFO/scripts/unityextract", line 143, in main
    exit(app.run())
  File "/usr/local/lib/python3.5/site-packages/unitypack-0.6.1-py3.5.egg/EGG-INFO/scripts/unityextract", line 49, in run
    self.handle_asset(asset)
  File "/usr/local/lib/python3.5/site-packages/unitypack-0.6.1-py3.5.egg/EGG-INFO/scripts/unityextract", line 81, in handle_asset
    for id, obj in asset.objects.items():
  File "/usr/local/lib/python3.5/site-packages/unitypack-0.6.1-py3.5.egg/unitypack/asset.py", line 83, in objects
    self.load()
  File "/usr/local/lib/python3.5/site-packages/unitypack-0.6.1-py3.5.egg/unitypack/asset.py", line 98, in load
    self.metadata_size = buf.read_uint()
AttributeError: '_io.BufferedReader' object has no attribute 'read_uint'
```

I'm running Python 3.5.2:

```
→ python3 -V
Python 3.5.2
```

And here's a list of my installed packages:

```
→ pip3 list
lz4 (0.8.2)
pip (9.0.1)
setuptools (30.2.0)
unitypack (0.6.1)
wheel (0.29.0)
```

Any help would be greatly appreciated. Thx!

**Comment by jleclanche** [comment]
Can you get me the file you're trying to extract?

**Comment by ghost** [comment]
@jleclanche I've just sent you an email (_to the address on your GitHub account_) with a link to the file. Didn't feel comfortable sharing it publicly since it's from a paid game. Hope that's ok?

**Comment by jleclanche** [comment]
I fixed this particular issue. It still doesn't load the file... I'll look into the further issues later.
