### ISSUE TITLE
Can't decode text

### ISSUE THREAD

**Issue by oddMLan** [HearthSim/UnityPack#19]
unityview.py

```
import unitypack

with open("specials.bundle") as f:
    bundle = unitypack.load(f)

    for id, object in asset.objects.items():
        # Let's say we only want TextAsset objects
        if object.type == "TextAsset":
            # We avoid reading the data, unless it's a TextAsset
            data = object.read()
            # The resulting `data` is a unitypack.engine.TextAsset instance
            print("Asset name:", data.name)
            print("Contents:", repr(data.script))
```

```
Traceback (most recent call last):
  File "D:\Users\Kim\Documents\test\bundles\unityview.py", line 4, in <module>
    bundle = unitypack.load(f)
  File "D:\Python\Python35\lib\site-packages\unitypack\__init__.py", line 11, in load
    return env.load(file)
  File "D:\Python\Python35\lib\site-packages\unitypack\environment.py", line 21, in load
    ret.load(file)
  File "D:\Python\Python35\lib\site-packages\unitypack\assetbundle.py", line 34, in load
    self.signature = buf.read_string()
  File "D:\Python\Python35\lib\site-packages\unitypack\utils.py", line 70, in read_string
    ret = self.read_cstring()
  File "D:\Python\Python35\lib\site-packages\unitypack\utils.py", line 83, in read_cstring
    c = self.read(1)
  File "D:\Python\Python35\lib\site-packages\unitypack\utils.py", line 60, in read
    return self.buf.read(*args)
  File "D:\Python\Python35\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 32: invalid continuation byte
```

sample files: https://puu.sh/sOXJZ/d2ac030dda.zip

**Comment by jleclanche** [comment]
You should be opening the file as binary. `with open("specials.bundle", "rb") as f`.
