### ISSUE TITLE
Error when loading bundle file

### ISSUE THREAD

**Issue by jack980517** [HearthSim/UnityPack#25]
```
>>> bundle=unitypack.load(f)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jack980517/python-modules/UnityPack/unitypack/__init__.py", line 11, in load
    return env.load(file)
  File "/home/jack980517/python-modules/UnityPack/unitypack/environment.py", line 21, in load
    ret.load(file)
  File "/home/jack980517/python-modules/UnityPack/unitypack/assetbundle.py", line 36, in load
    self.signature = buf.read_string()
  File "/home/jack980517/python-modules/UnityPack/unitypack/utils.py", line 70, in read_string
    ret = self.read_cstring()
  File "/home/jack980517/python-modules/UnityPack/unitypack/utils.py", line 83, in read_cstring
    c = self.read(1)
  File "/home/jack980517/python-modules/UnityPack/unitypack/utils.py", line 60, in read
    return self.buf.read(*args)
  File "/usr/lib64/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9d in position 37: invalid start byte
```

**Comment by jack980517** [comment]
Solved: instead of `open("example.unity3d")` as written in the readme, `open("example.unity3d",'rb')` is required. Not specifying `rb` would result in the file being read as text rather than binary, and would have some weird issues like this one.
