### ISSUE TITLE
UnityPack does not work

### ISSUE THREAD

**Issue by NunzioArdi** [HearthSim/UnityPack#39]
I created a file "extract unity3d.py"
I wrote there : 

```
import unitypack

with open("movies0.unity3d", "rb") as f:
	bundle = unitypack.load(f)

	for asset in bundle.assets:
		print("%s: %s:: %i objects" % (bundle, asset, len(asset.objects)))

for id, object in asset.objects.items():
	# Let's say we only want TextAsset objects
	if object.type == "TextAsset":
		# We avoid reading the data, unless it's a TextAsset
		data = object.read()
		# The resulting `data` is a unitypack.engine.TextAsset instance
		print("Asset name:", data.name)
		print("Contents:", repr(data.script))
```

I have installed python 3.6 as well as libraries with pip:
- Unitypack (0.7.2)
- lz4 (0.9.0)
- Pillow (4.0.0)
- decrunch [unknown 0.0.0]
Bur the "decrunch" library installs by calling itself unknown.
I have the following error message :
```
Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
======== RESTART: C:\Users\Administrateur\Desktop\extract unity3d.py ========
Traceback (most recent call last):
  File "C:\Users\Administrateur\Desktop\extract unity3d.py", line 1, in <module>
    import unitypack
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\unitypack\__init__.py", line 4, in <module>
    __version__ = pkg_resources.require("unitypack")[0].version
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\pkg_resources\__init__.py", line 967, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\pkg_resources\__init__.py", line 853, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'decrunch' distribution was not found and is required by unitypack
>>> 
```
You have an idea of what I can do?

Translate by Google Translate

**Comment by NunzioArdi** [comment]
```
pip install --upgrade setuptools
pip install decrunch
```
