### ISSUE TITLE
OverflowError when unpacking UnityFS

### ISSUE THREAD

**Issue by Dakiel** [HearthSim/UnityPack#49]
```
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    bundle.assets[0].objects
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\unitypack\asset.py", line 83, in objects
    self.load()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\unitypack\asset.py", line 108, in load
    self.tree.load(buf)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\unitypack\type.py", line 132, in load
    tree.load(buf)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\unitypack\type.py", line 32, in load
    self.load_blob(buf)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\unitypack\type.py", line 54, in load_blob
    node_data = BytesIO(buf.read(24 * num_nodes))
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\unitypack\utils.py", line 58, in read
    return self.buf.read(*args)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\unitypack\assetbundle.py", line 189, in read
    part = self.current_stream.read(size)
OverflowError: Python int too large to convert to C ssize_t
```

Sorry to bother, but I've tried several UnityFS file and neither of them works.

Don't know why cannot upload zip file.
You can download it here .
https://www.sendspace.com/file/z1b0sm

**Comment by jleclanche** [comment]
@ifeherva Is your version affected?
