### ISSUE TITLE
Issue when trying to extract uiscreens0.unity3d

### ISSUE THREAD

**Issue by Paratron** [HearthSim/UnityPack#5]
The extract.py script fails with the following traceback:

``` pytb
Traceback (most recent call last):
  File "extract.py", line 98, in <module>
    main()
  File "extract.py", line 94, in main
    handle_asset(asset)
  File "extract.py", line 37, in handle_asset
    if obj.type not in SUPPORTED_FORMATS:
  File "f:\python\python-unitypack\unitypack\__init__.py", line 196, in type
    typename = script.resolve()["m_ClassName"]
AttributeError: 'NoneType' object has no attribute 'resolve'
```

**Comment by andburn** [comment]
@jleclanche problem is an object in `uiscreens0` with a `type_id` of _-150_, that has no script pointer.

```
{'m_GameObject': ObjectPointer(file_id=0, path_id=-649827629176584049), 'm_Name': '', 'm_Enabled': 1, 'm_Script': None}
```

Not sure how to fix it, except `abs` on the `type_id`, but I guess there must be some reason they can be negative?

**Comment by jleclanche** [comment]
I'm not sure actually. @Mischanix any idea?
