### ISSUE TITLE
(UnityExtract) Class ID:  KeyError: -14

### ISSUE THREAD

**Issue by Avatarchik** [HearthSim/UnityPack#63]
UnityPack Version:0.8.1
file: https://drive.google.com/open?id=1u39GZ2llpNWJAH80rrjtvnZxPYz4SGMP

How to skip classes with id <0?

WARNING:root:-14 absent from structs.dat
WARNING:root:-6 absent from structs.dat
WARNING:root:-16 absent from structs.dat
WARNING:root:-10 absent from structs.dat
WARNING:root:-22 absent from structs.dat
WARNING:root:-33 absent from structs.dat
WARNING:root:-9 absent from structs.dat
WARNING:root:-18 absent from structs.dat
WARNING:root:-25 absent from structs.dat
WARNING:root:-8 absent from structs.dat
WARNING:root:-3 absent from structs.dat
WARNING:root:-23 absent from structs.dat
WARNING:root:-32 absent from structs.dat
WARNING:root:-31 absent from structs.dat
WARNING:root:-12 absent from structs.dat
WARNING:root:-28 absent from structs.dat
WARNING:root:-19 absent from structs.dat
WARNING:root:-20 absent from structs.dat
WARNING:root:-30 absent from structs.dat
WARNING:root:-29 absent from structs.dat
WARNING:root:-4 absent from structs.dat
WARNING:root:-2 absent from structs.dat
WARNING:root:-15 absent from structs.dat
WARNING:root:-27 absent from structs.dat
WARNING:root:-24 absent from structs.dat
WARNING:root:-17 absent from structs.dat
WARNING:root:-35 absent from structs.dat
WARNING:root:-7 absent from structs.dat
WARNING:root:-26 absent from structs.dat
WARNING:root:-5 absent from structs.dat
WARNING:root:-21 absent from structs.dat
WARNING:root:-11 absent from structs.dat
WARNING:root:-13 absent from structs.dat
WARNING:root:-34 absent from structs.dat
Traceback (most recent call last):
  File "d:\Projects\Other\UNITYPACK\UnityPack-master\bin\unityextract", line 173, in <module>
    main()
  File "d:\Projects\Other\UNITYPACK\UnityPack-master\bin\unityextract", line 169, in main
    exit(app.run())
  File "d:\Projects\Other\UNITYPACK\UnityPack-master\bin\unityextract", line 74, in run
    self.handle_asset(asset)
  File "d:\Projects\Other\UNITYPACK\UnityPack-master\bin\unityextract", line 107, in handle_asset
    if obj.type not in self.handle_formats:
  File "d:\Projects\Other\UNITYPACK\UnityPack-master\bin\..\unitypack\object.py", line 30, in type
    script = self.read()["m_Script"]
  File "d:\Projects\Other\UNITYPACK\UnityPack-master\bin\..\unitypack\object.py", line 84, in read
    return self.read_value(self.type_tree, BinaryReader(BytesIO(object_buf)))
  File "d:\Projects\Other\UNITYPACK\UnityPack-master\bin\..\unitypack\object.py", line 51, in type_tree
    return TypeMetadata.default(self.asset).type_trees[self.class_id]
KeyError: -14

**Comment by loeffel-io** [comment]
belongs to #100
