### ISSUE TITLE
pkg_resources.DistributionNotFound: 'unitypack'

### ISSUE THREAD

**Issue by fireundubh** [HearthSim/UnityPack#65]
When I try to run `unityextract`, I get a `pkg_resources.DistributionNotFound` error. I don't see any issues with imports in PyCharm, so I'm at a loss as to why this is occurring.

```
D:\dev\Python363\python.exe -m bin.unityextract "E:\SteamLibrary\Pillars of Eternity\PillarsOfEternity_Data\assetbundles\prefabs\objectbundle\gem_velune_125cp.unity3d"
Traceback (most recent call last):
  File "D:\dev\Python363\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\dev\Python363\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\projects\UnityPack\bin\unityextract.py", line 7, in <module>
    import unitypack
  File "E:\projects\UnityPack\unitypack\__init__.py", line 6, in <module>
    __version__ = pkg_resources.require(r'unitypack')[0].version
  File "D:\dev\Python363\lib\site-packages\pkg_resources\__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "D:\dev\Python363\lib\site-packages\pkg_resources\__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'unitypack' distribution was not found and is required by the application
```

**Comment by fireundubh** [comment]
Nevermind! Solution: `pip install unitypack` LOL
