### ISSUE TITLE
Can't extract ogg files with unityextract

### ISSUE THREAD

**Issue by Lykrast** [HearthSim/UnityPack#82]
Trying to extract ogg files with the unityextract script but it keeps giving that error:

```
Traceback (most recent call last):
  File "unityextract", line 159, in <module>
    main()
  File "unityextract", line 155, in main
    exit(app.run())
  File "unityextract", line 57, in run
    self.handle_asset(asset)
  File "unityextract", line 97, in handle_asset
    samples = extract_audioclip_samples(d)
  File "C:\Users\Lykrast\AppData\Local\Programs\Python\Python36-32\lib\site-packages\unitypack\utils.py", line 37, in extract_audioclip_samples
    sample = af.rebuild_sample(sample)
  File "C:\Users\Lykrast\AppData\Local\Programs\Python\Python36-32\lib\site-packages\fsb5\__init__.py", line 212, in rebuild_sample
    from . import vorbis
  File "C:\Users\Lykrast\AppData\Local\Programs\Python\Python36-32\lib\site-packages\fsb5\vorbis.py", line 12, in <module>
    vorbis = load_lib('vorbis')
  File "C:\Users\Lykrast\AppData\Local\Programs\Python\Python36-32\lib\site-packages\fsb5\utils.py", line 76, in load_lib
    raise LibraryNotFoundException('Could not load the library %r' % (names[0]))
fsb5.utils.LibraryNotFoundException: Could not load the library 'vorbis'
```

* Windows 10 64 bit version 1803
* unitypack and fsb5 installed with pip

I have tried putting the libvorbis and libogg libs given on the fsb5 github in multiple places, including:

* `C:\Windows\System32`
* Where the unityextract script is `C:\Users\Lykrast\AppData\Local\Programs\Python\Python36-32\Scripts`
* Where unitypack is installed `C:\Users\Lykrast\AppData\Local\Programs\Python\Python36-32\Lib\site-packages\unitypack`
* Where fsb5 is installed `C:\Users\Lykrast\AppData\Local\Programs\Python\Python36-32\Lib\site-packages\fsb5`

So far none of them worked and the error hasn't changed.

**Comment by Lykrast** [comment]
Just noticed that I got the issue duplicated at #83, probably something wonky happened with my internet connection when I wrote that.
