### ISSUE TITLE
struct.error: unpack requires a buffer of 4 bytes

### ISSUE THREAD

**Issue by FosterZRussian** [HearthSim/UnityPack#98]
E:\FosterZ\RED-ZM CF\cfmch25022020\assets\Assets\UnityPack-0.9.0>py use.py --models sharedw3_1.unity3d
Traceback (most recent call last):
  File "use.py", line 159, in <module>
    main()
  File "use.py", line 155, in main
    exit(app.run())
  File "use.py", line 57, in run
    self.handle_asset(asset)
  File "use.py", line 92, in handle_asset
    d = obj.read()
  File "E:\FosterZ\RED-ZM CF\cfmch25022020\assets\Assets\UnityPack-0.9.0\unitypack\object.py", line 84, in read
    return self.read_value(self.type_tree, BinaryReader(BytesIO(object_buf)))
  File "E:\FosterZ\RED-ZM CF\cfmch25022020\assets\Assets\UnityPack-0.9.0\unitypack\object.py", line 149, in read_value
    result[child.name] = self.read_value(child, buf)
  File "E:\FosterZ\RED-ZM CF\cfmch25022020\assets\Assets\UnityPack-0.9.0\unitypack\object.py", line 117, in read_value
    size = buf.read_uint()
  File "E:\FosterZ\RED-ZM CF\cfmch25022020\assets\Assets\UnityPack-0.9.0\unitypack\utils.py", line 105, in read_uint
    return struct.unpack(self.endian + "I", self.read(4))[0]
struct.error: unpack requires a buffer of 4 bytes

[sharedw3_1.zip](https://github.com/HearthSim/UnityPack/files/4252312/sharedw3_1.zip)

**Comment by dialupdisaster** [comment]
Same problem :( It's been a year did you happen to find a solution for this @FosterZRussian ?
